compressorConfig:
  bits_per_codevector: 1
  epochs: 3
  initial_learning_rate: 0.7
  output_neurons: 10
imageHandlerConfig:
  image_location: Lenna.png
  block_width: 8
  block_height: 8
  training_frames: 100