compressorConfig:
  epochs: 3
  initial_learning_rate: 0.2
  number_of_neurons: 30
imageHandlerConfig:
  image_location: Lenna.png
  block_width: 4
  block_height: 4
  RGB: true
  training_frames: 5000