compressorConfig:
  epochs: 1
  initial_learning_rate: 0.2
  number_of_neurons: 20
imageHandlerConfig:
  image_location: Lenna.png
  block_width: 4
  block_height: 4
  RGB: false
  training_frames: 5000