compressorConfig:
  bits_per_codevector: 8
  epochs: 3
  initial_learning_rate: 0.7
  output_neurons: 10
imageHandlerConfig:
  image_location: Lenna.png
  block_width: 16
  block_height: 16
  RGB: true
  training_frames: 4097